name: Request Copilot Review

on:
  pull_request:
    types: [opened, reopened]

jobs:
  request-review:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read

    steps:
      - name: Request Copilot Review
        run: |
          gh pr review ${{ github.event.pull_request.number }} --request-changes --body "🤖 GitHub Copilot Review Requested\n\nI'll review this PR and provide feedback on the code changes."
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} 